print("TUPLAS")
print("----------------------")
#Tuplas
print("Creación de una tuplas")
materias = ("Cálculo", "Álgebra Lineal", "Química")
print(materias)
print("----------------------")
print("Creación de una tuplas")
materias = ("Cálculo",)
print(materias)
print(type(materias))
print("----------------------")
print("Creación de una tuplas")
materias = tuple(("Cálculo", "Álgebra Lineal", "Cálculo"))
print(materias)
print("----------------------")